"""
Scheduling Manager
Handles automated task scheduling via cron
"""

import re
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Tuple
from .utils import logger
from .config import get_config


class SchedulingManager:
    """Manages automated task scheduling"""

    BACKUP_QUEUE = [
        {'service': 'credentials',       'frequency': 'daily',  'offset_minutes': -5},
        {'service': 'nginx',             'frequency': 'daily',  'offset_minutes': 0},
        {'service': 'mailcow-directory', 'frequency': 'daily',  'offset_minutes': 30},
        {'service': 'mailcow',           'frequency': 'daily',  'offset_minutes': 60},
        {'service': 'server-manager',    'frequency': 'daily',  'offset_minutes': 180},
        {'service': 'monitoring-stack',  'frequency': 'daily',  'offset_minutes': 210},
    ]

    BACKUP_WINDOWS = {
        'night':     {'hour': 2,  'label': 'Night (02:00)'},
        'morning':   {'hour': 8,  'label': 'Morning (08:00)'},
        'afternoon': {'hour': 14, 'label': 'Afternoon (14:00)'},
        'evening':   {'hour': 20, 'label': 'Evening (20:00)'},
    }

    def __init__(self):
        """Initialize scheduling manager"""
        self.config = get_config()
        self.cron_user = "root"
        self.schedule_dir = Path("/opt/server-manager/schedules")
        self.schedule_dir.mkdir(parents=True, exist_ok=True)

        logger.info("SchedulingManager initialized")

    def get_current_schedule(self) -> Dict[str, any]:
        """
        Get current cron schedule

        Returns:
            Dictionary containing current schedule information
        """
        try:
            result = subprocess.run(
                ["crontab", "-l"],
                capture_output=True,
                text=True
            )

            if result.returncode != 0:
                # No crontab exists yet
                return {
                    'exists': False,
                    'jobs': [],
                    'raw': ''
                }

            cron_content = result.stdout
            jobs, preserved = self._parse_crontab(cron_content)

            return {
                'exists': True,
                'jobs': jobs,
                'preserved': preserved,
                'raw': cron_content
            }

        except Exception as e:
            logger.error(f"Failed to get cron schedule: {e}")
            raise

    # Lines we generate ourselves on every write — never treated as preserved,
    # otherwise they would duplicate on each rewrite.
    GENERATED_COMMENT_PREFIXES = (
        '# server-manager',
        '# Generated by SchedulingManager',
        '# Last updated:',
        '# Environment',
        '# Preserved entries',
    )
    GENERATED_ENV_LINES = (
        'SHELL=/bin/bash',
        'PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin',
        'MAILTO=root',
    )

    # Charset of a standard cron time field (numbers, *, lists, ranges, steps)
    _CRON_FIELD_RE = re.compile(r'^[\d*,/-]+$')

    def _parse_crontab(self, content: str) -> Tuple[List[Dict[str, str]], List[str]]:
        """
        Parse crontab content into (jobs, preserved_lines).

        Standard 5-field jobs are parsed into job dictionaries. Everything
        else that isn't one of our own generated header lines — @reboot
        entries, environment variables, manual comments — is preserved
        verbatim so rewriting the crontab never silently deletes it.

        Args:
            content: Raw crontab content

        Returns:
            Tuple of (job dictionaries, preserved raw lines)
        """
        jobs = []
        preserved = []

        for line in content.split('\n'):
            line = line.strip()

            if not line:
                continue

            # Skip our own generated env header lines
            if line in self.GENERATED_ENV_LINES:
                continue

            if line.startswith('#'):
                # Skip our own generated comments; keep manual ones
                if not line.startswith(self.GENERATED_COMMENT_PREFIXES):
                    preserved.append(line)
                continue

            # Parse as a standard cron job only if the first five fields
            # look like cron time fields — otherwise preserve verbatim
            # (@reboot entries, env vars like TZ=..., malformed lines)
            parts = line.split(None, 5)
            if len(parts) >= 6 and all(self._CRON_FIELD_RE.match(p) for p in parts[:5]):
                jobs.append({
                    'minute': parts[0],
                    'hour': parts[1],
                    'day': parts[2],
                    'month': parts[3],
                    'weekday': parts[4],
                    'command': parts[5],
                    'schedule': f"{parts[0]} {parts[1]} {parts[2]} {parts[3]} {parts[4]}",
                    'type': self._identify_job_type(parts[5])
                })
            else:
                preserved.append(line)

        return jobs, preserved

    def _identify_job_type(self, command: str) -> str:
        """
        Identify the type of scheduled job by extracting the service name
        from the automated-backup.sh command.

        Args:
            command: Cron command

        Returns:
            Job type identifier (e.g., 'backup_nginx', 'backup_monitoring-stack')
        """
        # Extract service name from: automated-backup.sh <service>
        match = re.search(r'automated-backup\.sh\s+(\S+)', command)
        if match:
            return f'backup_{match.group(1)}'

        if 'borg-check' in command:
            return 'borg_check'
        elif 'gandi-token-renew' in command:
            return 'gandi_token_renew'
        elif 'cleanup' in command:
            return 'cleanup'
        elif 'update' in command:
            return 'update'
        elif 'health-check' in command:
            return 'health_check'
        elif 'weekly-summary' in command:
            return 'weekly_summary'
        elif 'memory-alert' in command:
            return 'memory_alert'
        else:
            return 'unknown'

    def schedule_backup_queue(self, window_key: str) -> bool:
        """
        Schedule all backups using the queue-based approach.

        Replaces all existing backup_* cron jobs with a sequenced set
        based on the chosen time window.

        Args:
            window_key: One of 'night', 'morning', 'afternoon', 'evening'

        Returns:
            True if scheduled successfully
        """
        try:
            window = self.BACKUP_WINDOWS.get(window_key)
            if not window:
                raise ValueError(f"Invalid backup window: {window_key}")

            start_hour = window['hour']

            # Build new backup jobs from the queue
            new_backup_jobs = []
            for entry in self.BACKUP_QUEUE:
                total_minutes = start_hour * 60 + entry['offset_minutes']
                cron_hour = total_minutes // 60
                cron_minute = total_minutes % 60

                if entry['frequency'] == 'daily':
                    schedule = f"{cron_minute} {cron_hour} * * *"
                else:  # weekly (Sunday)
                    schedule = f"{cron_minute} {cron_hour} * * 0"

                cmd = self._build_backup_command(entry['service'], {'verify': True})

                new_backup_jobs.append({
                    'minute': str(cron_minute),
                    'hour': str(cron_hour),
                    'day': '*',
                    'month': '*',
                    'weekday': '*' if entry['frequency'] == 'daily' else '0',
                    'command': cmd,
                    'schedule': schedule,
                    'type': f"backup_{entry['service']}"
                })

            # Get current crontab and remove all existing backup_* jobs
            current = self.get_current_schedule()
            non_backup_jobs = [
                j for j in current.get('jobs', [])
                if not j['type'].startswith('backup_')
            ]

            # Combine non-backup jobs with new backup queue
            all_jobs = non_backup_jobs + new_backup_jobs

            # Write the full crontab (carrying over preserved lines)
            self._write_crontab(all_jobs, current.get('preserved', []))

            # Persist the window choice in config
            self.config.set('backup.window', window_key)
            self.config.save_config()

            logger.info(f"Backup queue scheduled with window '{window_key}' (start: {start_hour:02d}:00)")
            return True

        except Exception as e:
            logger.error(f"Failed to schedule backup queue: {e}")
            return False

    def get_backup_queue_description(self, window_key: str) -> str:
        """
        Return a formatted preview of the backup queue for a given window.

        Args:
            window_key: One of 'night', 'morning', 'afternoon', 'evening'

        Returns:
            Formatted string showing each service, its time, and frequency
        """
        window = self.BACKUP_WINDOWS.get(window_key)
        if not window:
            return f"Unknown window: {window_key}"

        start_hour = window['hour']
        lines = [f"Backup Queue - {window['label']}", "=" * 50, ""]
        lines.append(f"{'Slot':<6}{'Service':<22}{'Time':<10}{'Frequency'}")
        lines.append("-" * 50)

        for i, entry in enumerate(self.BACKUP_QUEUE, 1):
            total_minutes = start_hour * 60 + entry['offset_minutes']
            h = total_minutes // 60
            m = total_minutes % 60
            time_str = f"{h:02d}:{m:02d}"
            freq = "Daily" if entry['frequency'] == 'daily' else "Weekly (Sun)"
            lines.append(f"{i:<6}{entry['service']:<22}{time_str:<10}{freq}")

        lines.append("")
        lines.append("Daily jobs run every night.")
        lines.append("Weekly jobs run on Sunday only.")

        return "\n".join(lines)

    # Valid value bounds per cron field: minute, hour, day, month, weekday
    # (weekday allows 0-7: both 0 and 7 mean Sunday)
    _CRON_FIELD_BOUNDS = [(0, 59), (0, 23), (1, 31), (1, 12), (0, 7)]

    def _validate_cron_schedule(self, schedule: str) -> bool:
        """
        Validate cron schedule expression

        Accepts standard syntax: numbers, *, comma lists, ranges (1-5),
        and steps (*/6, 1-5/2).

        Args:
            schedule: Cron schedule (e.g., "0 2 * * *")

        Returns:
            True if valid
        """
        parts = schedule.split()
        if len(parts) != 5:
            return False

        item_re = re.compile(r'^(\*|(\d+)(?:-(\d+))?)(?:/(\d+))?$')

        for field, (lo, hi) in zip(parts, self._CRON_FIELD_BOUNDS):
            for item in field.split(','):
                m = item_re.match(item)
                if not m:
                    return False

                _, start, end, step = m.groups()

                if start is not None:
                    if not (lo <= int(start) <= hi):
                        return False
                    if end is not None and not (int(start) <= int(end) <= hi):
                        return False

                if step is not None and int(step) == 0:
                    return False

        return True

    def _build_backup_command(self, service: str, options: Dict) -> str:
        """
        Build backup command for cron with flock to prevent concurrent runs

        Args:
            service: Service name
            options: Backup options

        Returns:
            Full command string
        """
        script_path = "/opt/server-manager/scripts/automated-backup.sh"
        log_file = f"/opt/server-manager/logs/backup-{service}-cron.log"
        lock_file = f"/tmp/backup-{service}.lock"

        backup_cmd = f"{script_path} {service}"

        if options.get('verify'):
            backup_cmd += " --verify"

        # Redirect output to log file
        backup_cmd += f" >> {log_file} 2>&1"

        # Wrap in flock to prevent concurrent runs
        cmd = f"flock -n {lock_file} {backup_cmd}"

        return cmd

    def _render_crontab(self, jobs: List[Dict[str, str]], preserved: List[str]) -> str:
        """
        Render crontab content from jobs and preserved lines.

        Pure string builder (no side effects) so the output can be
        verified/tested without installing it.

        Args:
            jobs: List of job dictionaries
            preserved: Raw lines to carry over verbatim

        Returns:
            Full crontab content as a string
        """
        lines = [
            "# server-manager automated schedules",
            "# Generated by SchedulingManager",
            f"# Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "# Environment",
            "SHELL=/bin/bash",
            "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin",
            "MAILTO=root",
            ""
        ]

        if preserved:
            lines.append("# Preserved entries (not managed by server-manager)")
            lines.extend(preserved)
            lines.append("")

        for job in jobs:
            job_type = job.get('type', 'unknown')
            lines.append(f"# server-manager: {job_type}")

            cron_line = f"{job['minute']} {job['hour']} {job['day']} {job['month']} {job['weekday']} {job['command']}"
            lines.append(cron_line)
            lines.append("")

        return '\n'.join(lines)

    def _backup_crontab(self) -> Optional[Path]:
        """
        Save the current crontab to schedules/crontab.backup.<timestamp>
        before any rewrite. Keeps the 5 most recent backups.

        Returns:
            Path of the backup file, or None if there was no crontab
        """
        result = subprocess.run(
            ["crontab", "-l"],
            capture_output=True,
            text=True
        )

        if result.returncode != 0 or not result.stdout.strip():
            return None

        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        backup_path = self.schedule_dir / f"crontab.backup.{timestamp}"
        backup_path.write_text(result.stdout)

        # Prune old backups, keep the 5 most recent
        backups = sorted(self.schedule_dir.glob('crontab.backup.*'))
        for old in backups[:-5]:
            old.unlink()

        logger.info(f"Crontab backed up to: {backup_path}")
        return backup_path

    def _write_crontab(
        self,
        jobs: List[Dict[str, str]],
        preserved: Optional[List[str]] = None
    ) -> bool:
        """
        Write crontab from job list, carrying over preserved lines.

        Args:
            jobs: List of job dictionaries
            preserved: Raw lines to keep verbatim. If None, they are
                       re-read from the current crontab so a caller can
                       never accidentally drop them.

        Returns:
            True if successful
        """
        try:
            if preserved is None:
                _, preserved = self._parse_crontab(
                    subprocess.run(
                        ["crontab", "-l"], capture_output=True, text=True
                    ).stdout or ''
                )

            # Safety net: keep a copy of what we're about to replace
            self._backup_crontab()

            content = self._render_crontab(jobs, preserved)

            # Write to temp file
            temp_file = self.schedule_dir / "crontab.tmp"
            with open(temp_file, 'w') as f:
                f.write(content)

            # Install crontab
            result = subprocess.run(
                ["crontab", str(temp_file)],
                capture_output=True,
                text=True
            )

            if result.returncode != 0:
                raise Exception(f"Failed to install crontab: {result.stderr}")

            # Clean up temp file
            temp_file.unlink()

            logger.info(f"Crontab updated successfully ({len(jobs)} jobs, {len(preserved)} preserved lines)")
            return True

        except Exception as e:
            logger.error(f"Failed to write crontab: {e}")
            raise

    def remove_schedule(self, job_type: str) -> bool:
        """
        Remove scheduled job

        Args:
            job_type: Type of job to remove

        Returns:
            True if removed successfully
        """
        try:
            current = self.get_current_schedule()

            if not current['exists']:
                return True

            # Filter out the job
            jobs = [j for j in current['jobs'] if j['type'] != job_type]

            if len(jobs) == len(current['jobs']):
                logger.warning(f"Job type {job_type} not found in schedule")
                return False

            # Write updated crontab
            self._write_crontab(jobs, current.get('preserved', []))

            logger.info(f"Removed schedule for {job_type}")
            return True

        except Exception as e:
            logger.error(f"Failed to remove schedule: {e}")
            return False

    def get_schedule_presets(self) -> Dict[str, str]:
        """
        Get predefined schedule presets

        Returns:
            Dictionary of preset name to cron schedule
        """
        return {
            'daily_2am': '0 2 * * *',
            'daily_3am': '0 3 * * *',
            'daily_4am': '0 4 * * *',
            'daily_midnight': '0 0 * * *',
            'weekly_sunday_2am': '0 2 * * 0',
            'weekly_monday_2am': '0 2 * * 1',
            'hourly': '0 * * * *',
            'every_6_hours': '0 */6 * * *',
            'every_12_hours': '0 */12 * * *'
        }

    def get_schedule_description(self, schedule: str) -> str:
        """
        Get human-readable description of cron schedule

        Args:
            schedule: Cron schedule expression

        Returns:
            Human-readable description
        """
        presets = {
            '0 2 * * *': 'Daily at 2:00 AM',
            '0 3 * * *': 'Daily at 3:00 AM',
            '0 4 * * *': 'Daily at 4:00 AM',
            '0 0 * * *': 'Daily at midnight',
            '0 2 * * 0': 'Weekly on Sunday at 2:00 AM',
            '0 2 * * 1': 'Weekly on Monday at 2:00 AM',
            '0 * * * *': 'Every hour',
            '0 */6 * * *': 'Every 6 hours',
            '0 */12 * * *': 'Every 12 hours'
        }

        return presets.get(schedule, f"Custom schedule: {schedule}")

    def schedule_cleanup(self, schedule: str, retention_days: int = 30) -> bool:
        """
        Schedule automated backup cleanup

        Args:
            schedule: Cron schedule expression
            retention_days: Days to retain backups

        Returns:
            True if scheduled successfully
        """
        try:
            if not self._validate_cron_schedule(schedule):
                raise ValueError(f"Invalid cron schedule: {schedule}")

            cmd = f"/opt/server-manager/scripts/cleanup-backups.sh {retention_days} >> /opt/server-manager/logs/cleanup-cron.log 2>&1"

            current = self.get_current_schedule()
            jobs = [j for j in current.get('jobs', []) if j['type'] != 'cleanup']

            jobs.append({
                'minute': schedule.split()[0],
                'hour': schedule.split()[1],
                'day': schedule.split()[2],
                'month': schedule.split()[3],
                'weekday': schedule.split()[4],
                'command': cmd,
                'schedule': schedule,
                'type': 'cleanup'
            })

            self._write_crontab(jobs, current.get('preserved', []))

            logger.info(f"Scheduled cleanup: {schedule} (retention: {retention_days} days)")
            return True

        except Exception as e:
            logger.error(f"Failed to schedule cleanup: {e}")
            return False

    def schedule_gandi_token_renewal(self) -> bool:
        """
        Schedule daily Gandi token renewal check at 12:00.

        Replaces any existing gandi_token_renew cron job.

        Returns:
            True if scheduled successfully
        """
        try:
            script_path = "/opt/server-manager/scripts/gandi-token-renew.sh"
            log_file = "/var/log/gandi-token-renew.log"
            lock_file = "/tmp/gandi-token-renew.lock"

            cmd = f"flock -n {lock_file} {script_path} >> {log_file} 2>&1"

            current = self.get_current_schedule()
            jobs = [j for j in current.get('jobs', []) if j['type'] != 'gandi_token_renew']

            jobs.append({
                'minute': '0',
                'hour': '12',
                'day': '*',
                'month': '*',
                'weekday': '*',
                'command': cmd,
                'schedule': '0 12 * * *',
                'type': 'gandi_token_renew'
            })

            self._write_crontab(jobs, current.get('preserved', []))

            logger.info("Scheduled Gandi token renewal: daily at 12:00")
            return True

        except Exception as e:
            logger.error(f"Failed to schedule Gandi token renewal: {e}")
            return False

    def schedule_borg_check(self) -> bool:
        """
        Schedule monthly Borg repository integrity check.

        Runs on the 1st of each month at 06:00 — after the nightly
        backup window (01:55-05:31) so borg repo locks never collide.
        Replaces any existing borg_check cron job.

        Returns:
            True if scheduled successfully
        """
        try:
            script_path = "/opt/server-manager/scripts/borg-check.sh"
            log_file = "/opt/server-manager/logs/borg-check-cron.log"
            lock_file = "/tmp/borg-check.lock"

            cmd = f"flock -n {lock_file} {script_path} >> {log_file} 2>&1"

            current = self.get_current_schedule()
            jobs = [j for j in current.get('jobs', []) if j['type'] != 'borg_check']

            jobs.append({
                'minute': '0',
                'hour': '6',
                'day': '1',
                'month': '*',
                'weekday': '*',
                'command': cmd,
                'schedule': '0 6 1 * *',
                'type': 'borg_check'
            })

            self._write_crontab(jobs, current.get('preserved', []))

            logger.info("Scheduled Borg repository check: 1st of month at 06:00")
            return True

        except Exception as e:
            logger.error(f"Failed to schedule Borg check: {e}")
            return False

    def schedule_weekly_summary(self) -> bool:
        """
        Schedule weekly health summary email at Sunday 08:00.

        Replaces any existing weekly_summary cron job.

        Returns:
            True if scheduled successfully
        """
        try:
            script_path = "/opt/server-manager/scripts/weekly-summary.sh"
            log_file = "/opt/server-manager/logs/weekly-summary-cron.log"
            lock_file = "/tmp/weekly-summary.lock"

            cmd = f"flock -n {lock_file} {script_path} >> {log_file} 2>&1"

            current = self.get_current_schedule()
            jobs = [j for j in current.get('jobs', []) if j['type'] != 'weekly_summary']

            jobs.append({
                'minute': '0',
                'hour': '8',
                'day': '*',
                'month': '*',
                'weekday': '0',
                'command': cmd,
                'schedule': '0 8 * * 0',
                'type': 'weekly_summary'
            })

            self._write_crontab(jobs, current.get('preserved', []))

            logger.info("Scheduled weekly summary: Sunday at 08:00")
            return True

        except Exception as e:
            logger.error(f"Failed to schedule weekly summary: {e}")
            return False

    def get_next_run_time(self, schedule: str) -> Optional[str]:
        """
        Calculate next run time for a schedule

        Args:
            schedule: Cron schedule expression

        Returns:
            Next run time as string, or None if cannot calculate
        """
        try:
            # This is a simplified version
            # For production, consider using python-crontab library
            parts = schedule.split()
            if len(parts) != 5:
                return None

            minute, hour = parts[0], parts[1]

            now = datetime.now()

            # Handle simple cases
            if minute == '*' and hour == '*':
                return "Next hour"
            elif minute.isdigit() and hour.isdigit():
                next_hour = int(hour)
                next_minute = int(minute)

                if now.hour > next_hour or (now.hour == next_hour and now.minute >= next_minute):
                    return f"Tomorrow at {next_hour:02d}:{next_minute:02d}"
                else:
                    return f"Today at {next_hour:02d}:{next_minute:02d}"

            return "See cron schedule"

        except Exception:
            return None
